package testcrud; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement; 
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aqshal-kun
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        settgl();
        setjm();
    }
    
    String nol_detik = "";
    String nol_menit = "";
    String nol_jam = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        tempat = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        perem = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jm = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(540, 30, 80, 30);

        print.setBackground(new java.awt.Color(0, 204, 204));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(710, 30, 80, 30);

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(140, 30, 80, 30);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(230, 30, 80, 30);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(320, 30, 80, 30);

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(420, 30, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 90, 850, 90);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "TempatLahir", "TanggalLahir", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 830, 490);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 200, 850, 510);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alamat");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 470, 130, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelas");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 350, 130, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIS");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 60, 130, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 410, 130, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 300, 130, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 120, 130, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Lahir");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 240, 130, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tempat Lahir");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 180, 130, 30);
        jPanel3.add(Tanggal);
        Tanggal.setBounds(20, 270, 260, 30);

        tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatActionPerformed(evt);
            }
        });
        jPanel3.add(tempat);
        tempat.setBounds(20, 210, 260, 30);
        jPanel3.add(nis);
        nis.setBounds(20, 90, 190, 30);

        buttonGroup1.add(perem);
        perem.setForeground(new java.awt.Color(255, 255, 255));
        perem.setText("Perempuan");
        jPanel3.add(perem);
        perem.setBounds(130, 330, 100, 23);

        buttonGroup1.add(laki);
        laki.setForeground(new java.awt.Color(255, 255, 255));
        laki.setText("Laki-laki");
        jPanel3.add(laki);
        laki.setBounds(20, 330, 90, 23);
        jPanel3.add(nama);
        nama.setBounds(20, 150, 260, 30);
        jPanel3.add(kelas);
        kelas.setBounds(20, 380, 80, 30);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 500, 260, 110);
        jPanel3.add(email);
        email.setBounds(20, 440, 260, 30);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 310, 560);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Form Isian");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 10, 240, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 90, 310, 620);

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Form Biodata SMK TELKOM MAGETAN");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(50, 10, 480, 50);

        jm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jm.setForeground(new java.awt.Color(255, 255, 255));
        jm.setText("Jam");
        jPanel4.add(jm);
        jm.setBounds(1020, 30, 170, 40);

        tgl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setText("Tanggal");
        jPanel4.add(tgl);
        tgl.setBounds(1020, 0, 170, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1210, 80);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1210, 720);

        setBounds(0, 0, 1227, 758);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        Date dateFormat = null;

        nama.setText("");
        nis.setText("");
        kelas.setText("");
        tempat.setText("");
        Tanggal.setDate(dateFormat);
        buttonGroup1.clearSelection();
        email.setText("");
        alamat.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        
        if("".equals(nis.getText()) || "".equals(nama.getText())  || "".equals(tempat.getText())  || "".equals(tanggal) 
                || "".equals(email.getText()) || "".equals(alamat.getText())  ){
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else {
            String JK = "";
            if (laki.isSelected()){
                JK = "L";
            }
            else{
                JK = "P";
            }
        
        
        String SQL = "INSERT INTO t_siswa(NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat) "+
                "VALUES('"+nis.getText()+"','"+nama.getText()+"','"+tempat.getText()+"','"+tanggal+"','"+JK+"','"+kelas.getText()+"','"+email.getText()+"','"+alamat.getText()+"')";
        int Status = KoneksiDB.execute(SQL);
        if (Status==1) {        
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        
        if( baris >= 0 ){
            String NIS = tabel.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int Status = KoneksiDB.execute(SQL);
        if (Status==1) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
        }
            
        }
        else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Dulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_refreshActionPerformed
 
    public void settgl(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new 
            java.text.SimpleDateFormat("dd/MM/yyyy");
        tgl.setText(kal.format(skrg));
    }
    
    public void setjm() {
ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jm.setText("Jam "+jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
    
    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
 
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            nis.setText(tabel.getValueAt(baris, 0).toString());
            nama.setText(tabel.getValueAt(baris, 1).toString());
            tempat.setText(tabel.getValueAt(baris, 2).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
             try {
                dateFormat = date.parse(tabel.getValueAt(baris, 3).toString());
            } catch (ParseException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }

            Tanggal.setDate(dateFormat);

            if ("Laki-laki".equals(tabel.getValueAt(baris, 4).toString())) {
                laki.setSelected(true);
            } else {
                perem.setSelected(true);
            }
            kelas.setText(tabel.getValueAt(baris, 5).toString());
            email.setText(tabel.getValueAt(baris, 6).toString());
            alamat.setText(tabel.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat ("Biodata Siswa SMK Telkom Magetan");
        MessageFormat footer = new MessageFormat ("Page {0,number,integer}   ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        if("".equals(nis.getText()) || "".equals(nama.getText())  || "".equals(tempat.getText())  || "".equals(tanggal) 
                || "".equals(email.getText()) || "".equals(alamat.getText())  ){
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else {
            String JK = "";
            if (laki.isSelected()){
                JK = "L";
            }
            else{
                JK = "P";
            }

            int baris = tabel.getSelectedRow();
            String nisi = tabel.getValueAt(baris, 0).toString();

            String SQL = "UPDATE `t_siswa` SET `NIS`='"+nis.getText()
            + "', `NamaSiswa`='"+nama.getText()
            + "', `TempatLahir`='"+tempat.getText()
            + "', `TanggalLahir`='"+tanggal
            + "', `JenisKelamin`='"+JK
            + "', `Kelas`='"+nama.getText()
            + "', `Email`='"+email.getText()
            + "', `Alamat`='"+alamat.getText()
            + "' WHERE NIS="+nisi;
            int Status = KoneksiDB.execute(SQL);
            if (Status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jm;
    private javax.swing.JTextField kelas;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JRadioButton perem;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tempat;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"NIS","NamaSiswa","TempatLahir","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
       DefaultTableModel dtm = new DefaultTableModel(null,kolom);
       String SQL = "SELECT * FROM `t_siswa`";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try {
           while(rs.next()){
               String NIS = rs.getString(1);
               String NamaSiswa = rs.getString(2);
               String TempatLahir = rs.getString(3);
               String TanggalLahir = rs.getString(4);
               String JenisKelamin = "";
               if ("L".equals(rs.getString(5))){
                   JenisKelamin = "Laki-Laki";
               }
               else{
                   JenisKelamin = "Perempuan";
               }
               String Kelas = rs.getString(6);
               String Email = rs.getString(7);
               String Alamat = rs.getString(8);
               String data[] = {NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
               dtm.addRow(data);
               
           }
       }
       catch (SQLException ex){
           Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
       }
       tabel.setModel(dtm);
    }  
   
}
